[package]
name = "tagger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comat = "0.1.3"
mindus = { version = "5.0.18", default-features = false }
